# 課題0628

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題１

- ```NumPy```を使って、最小二乗法で重回帰分析の係数を推定する関数を作成しよう。
- 与えられたデータで実装して動作を確認せよ。

In [1]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 1.4 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 11.4 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
def get_PartialRegressionCoefficient(X,y):
   X = np.hstack([np.ones((X.shape[0], 1)), X])
   beta = (np.linalg.inv(X.T @ X)) @ (X.T @ y)
   return beta

In [3]:
pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 2.6 MB/s eta 0:00:00
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 21.5 MB/s eta 0:00:0000:0100:01
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 8.8 MB/s eta 0:00:0000:0100:01m
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
# このコードを実行し、データの読み込み
# もしsklearnがインストールされていない場合は、!pip install sklearnを実行してください
from sklearn.datasets import load_iris
iris = load_iris()
# Irisデータセットをロード
iris = load_iris()
X = iris.data  # 説明変数のデータ
Y = iris.data[:, 1]  # 目的変数のデータ（がく片の幅）
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(Y)

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9
 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2
 3.3 3.  2.5 3.  3.4 3. ]


In [6]:
# Yを従属変数、Xを独立変数として、線形回帰モデルを作成し、回帰係数を求める
coefficients = get_PartialRegressionCoefficient(X, Y)
coefficients

array([-1.70530257e-13,  1.42108547e-14,  1.00000000e+00,  1.42108547e-14,
        0.00000000e+00])

In [7]:
pip install statsmodels

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 22.9 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 21.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 13.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 18.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [11]:
from sklearn.linear_model import LinearRegression

# 创建线性回归模型
model = LinearRegression()

# 训练模型
model.fit(X, Y)

# 输出回归系数
print("回归系数 (回归参数):")
print("截距:", model.intercept_)
print("系数:", model.coef_)

回归系数 (回归参数):
截距: -1.3322676295501878e-15
系数: [ 0.00000000e+00  3.11767721e-16  1.00000000e+00 -5.09971419e-17
 -2.63074542e-17]


## 課題2

以下の指示に従ってクラスを作成してください。

- クラスをインスタント化する際は二つ同じサイズの```ndarray```($v_1$と$v_2$)が渡されます
- クラスに$v_1$と$v_2$が同じサイズであるかどうかを確認するメソッドを実装しよう
- クラスに$v_1$が$v_2$に射影する結果を計算するメソッドを実装しよう
- クラスに$v_1$と$v_2$のコサイン類似度を計算するメソッドを実装しよう

In [ ]:
import numpy as np

class Vector:
    def __init__(self, v1, v2):
        self.v1 = v1
        self.v2 = v2
    
    def check_same_size(self):
        return self.v1.shape == self.v2.shape
    
    def projection(self):
        v2_norm = np.linalg.norm(self.v2)
        if v2_norm == 0:
            return np.zeros_like(self.v1)
        projection = (np.dot(self.v1, self.v2) / v2_norm**2) * self.v2
        return projection
    
    def cosine_similarity(self):
        dot_product = np.dot(self.v1, self.v2)
        norm_v1 = np.linalg.norm(self.v1)
        norm_v2 = np.linalg.norm(self.v2)
        if norm_v1 == 0 or norm_v2 == 0:
            return 0.0
        return dot_product / (norm_v1 * norm_v2)


In [ ]:
# 確認
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [ ]:
vector_instance = Vector(v1, v2)
print("同じサイズであるかどうか:", vector_instance.check_same_size())
print("射影する結果:", vector_instance.projection())
print("コサインの類似度:", vector_instance.cosine_similarity())

同じサイズであるかどうか: True
射影する結果: [1.66233766 2.07792208 2.49350649]
コサインの類似度: 0.9746318461970762
