# 課題0628

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題１

- ```NumPy```を使って、最小二乗法で重回帰分析の係数を推定する関数を作成しよう。
- 与えられたデータで実装して動作を確認せよ。

$$
\beta = (X^TX)^{-1}X^TY
$$

- [転置](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)
```
numpy.transpose(a, axes=None)
```

- [逆行列](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)
```
numpy.linalg.inv(a)
```

In [3]:
# このコードを実行し、データの読み込み
# もしsklearnがインストールされていない場合は、!pip install sklearnを実行してください
from sklearn.datasets import load_iris
iris = load_iris()
# Irisデータセットをロード
iris = load_iris()
X = iris.data  # 説明変数のデータ
Y = iris.data[:, 1]  # 目的変数のデータ（がく片の幅）

In [4]:
import numpy as np
def get_PartialRegressionCoefficient(x,y):
    xt= np.transpose(x)
    xtx= np.dot(xt,x)
    xtX_inv= np.linalg.inv(xtx)
    xty= np.dot(xt,y)
     
    return np.dot(xtX_inv,xty)

In [6]:
# Yを従属変数、Xを独立変数として、線形回帰モデルを作成し、回帰係数を求める
get_PartialRegressionCoefficient(X,Y)

array([ 9.94759830e-14,  1.00000000e+00, -7.10542736e-14,  1.06581410e-13])

[numpy.linalg.lstsq](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html)

In [7]:
np.linalg.lstsq(X,Y,rcond=None)[0]

array([-1.72041374e-16,  1.00000000e+00,  1.11022302e-16, -1.11022302e-16])

## 課題2

以下の指示に従ってクラスを作成してください。

- クラスをインスタント化する際は二つ同じサイズの```ndarray```($v_1$と$v_2$)が渡されます
- クラスに$v_1$と$v_2$が同じサイズであるかどうかを確認するメソッドを実装しよう
- クラスに$v_1$が$v_2$に射影する結果を計算するメソッドを実装しよう
- クラスに$v_1$と$v_2$のコサイン類似度を計算するメソッドを実装しよう

In [10]:
class Vector:
    def __init__(self, v1, v2):
        self.v1 = v1
        self.v2 = v2
    
    def check_size(self):
        if self.v1.shape == self.v2.shape:
            print("v1 and v2 have the same size.")
        else:
            print("v1 and v2 have different sizes.")
    
    def projection(self):
        dot_product = np.dot(self.v1, self.v2)
        norm_squared = np.dot(self.v2, self.v2)
        result = (dot_product / norm_squared) * self.v2
        return result
    
    def cosine_similarity(self):
        dot_product = np.dot(self.v1, self.v2)
        norm_v1 = np.linalg.norm(self.v1)
        norm_v2 = np.linalg.norm(self.v2)
        similarity = dot_product / (norm_v1 * norm_v2)
        return similarity

In [11]:
# 確認
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [12]:
vector = Vector(v1, v2)

In [13]:
vector.check_size()

v1 and v2 have the same size.


In [14]:
vector.projection()

array([1.66233766, 2.07792208, 2.49350649])

In [15]:
vector.cosine_similarity()

0.9746318461970762